swagger-ui:
  image: swaggerapi/swagger-ui
  container_name: swagger_ui_container
  ports:
    - "5030:8080"
  volumes:
    - ./api-endpoints:/usr/share/nginx/html/doc
  environment:
    API_URL: doc/api-endpoints.yaml